config/routes.rb
Domotic::Application.routes.draw do

  root :to => 'home#index'

  resources :rooms do
    resources :devices
  end

  namespace 'api' do
    resources :rooms do
      resources :devices, only: :index
      resources :lamps, only: [:index, :show, :on, :off, :on_all, :off_all] do
        post :on, on: :member
        post :off, on: :member

        post :on_all, on: :collection
        post :off_all, on: :collection
      end
      resources :dimmer_lamps, only: [:index, :show, :update]
    end
  end

end

app/models/device.rb
# == Schema Information
#
# Table name: devices
#
#  id          :integer          not null, primary key
#  room_id     :integer
#  type        :string(255)
#  name        :string(255)
#  description :text
#  status      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Device < ActiveRecord::Base

  # Attr accesible
  #----------------------------------------------------------------------
  attr_accessible :description, :name, :status, :type

  # associations
  #----------------------------------------------------------------------

  belongs_to :room


  # Return the user type downcased, dasherized and symbolized
  # ej: SuperUser -> :super_user
  def device_type
    ActiveModel::Naming.param_key(self)
  end



  # Return the user type downcased, dasherized and symbolized
  # ej: SuperUser -> :super_user
  def device_controller
    self.device_type.pluralize
  end

end

app/models/dimmer_lamp.rb
# == Schema Information
#
# Table name: devices
#
#  id          :integer          not null, primary key
#  room_id     :integer
#  type        :string(255)
#  name        :string(255)
#  description :text
#  status      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class DimmerLamp < Device


  def status
    read_attribute(:status) || 0
  end

end

app/models/lamp.rb
# == Schema Information
#
# Table name: devices
#
#  id          :integer          not null, primary key
#  room_id     :integer
#  type        :string(255)
#  name        :string(255)
#  description :text
#  status      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Lamp < Device

  def status
    status = read_attribute(:status) || 0
    status >  0
  end

  def on!
    update_attribute :status, 255
  end

  def off!
    update_attribute :status, 0
  end

  def on?
    self.status == true
  end

  def off?
    self.status == false
  end

end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Room < ActiveRecord::Base

  # Attributes access
  #----------------------------------------------------------------------

  attr_accessible :description, :name

  # assiciatons
  #----------------------------------------------------------------------

  has_many :devices, dependent: :destroy
  has_many :lamps
  has_many :dimmer_lamps

end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  respond_to :js

end

app/controllers/api/devices_controller.rb
class Api::DevicesController < Api::ApiController
  def index
    @room = Room.find params[:room_id]
    @devices = @room.devices
  end

end

app/controllers/api/dimmer_lamps_controller.rb
class Api::DimmerLampsController < Api::ApiController

  def index
    @room = Room.find params[:room_id]
    @dimmer_lamps = @room.dimmer_lamps
  end

  def show
    @room = Room.find params[:room_id]
    @dimmer_lamp = @room.dimmer_lamps.find params[:id]
  end


  def update
    @room = Room.find params[:room_id]
    @dimmer_lamp = @room.dimmer_lamps.find params[:id]
    if @dimmer_lamp.update_attribute :status, params[:status]
      render :show
    else
      render text: 'APP_ERROR', status: 500
    end
  end
end

app/controllers/api/lamps_controller.rb
class Api::LampsController < Api::ApiController

  def index
    @room = Room.find params[:room_id]
    @lamps = @room.lamps
  end

  def show
    @room = Room.find params[:room_id]
    @lamp = @room.lamps.find params[:id]
  end

  def on
    @room = Room.find params[:room_id]
    @lamp = @room.lamps.find params[:id]
    render text: 'APP_ERROR', status: 500 and return unless @lamp.on!
    render :show
  end

  def off
    @room = Room.find params[:room_id]
    @lamp = @room.lamps.find params[:id]
    render text: 'APP_ERROR', status: 500 and return unless @lamp.off!
    render :show
  end

  def on_all
    @room = Room.find params[:room_id]
    @lamps = @room.lamps
    @lamps.each do |lamp|
      lamp.on!
    end
    render :index
  end

  def off_all
    @room = Room.find params[:room_id]
    @lamps = @room.lamps
    @lamps.each do |lamp|
      lamp.off!
    end
    render :index
  end
end

app/controllers/api/rooms_controller.rb
class Api::RoomsController < Api::ApiController

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find params[:id]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
    @room = Room.find params[:room_id]
    @devices = @room.devices
  end

  def show
    @room = Room.find params[:room_id]
    @device = @room.devices.find params[:id]
  end

  def edit
    @room = Room.find params[:room_id]
    @device = @room.devices.find params[:id]
  end

  def new
    @room = Room.find params[:room_id]
    @device = @room.devices.new
  end

  def create
    @room = Room.find params[:room_id]
    @device = @room.devices.new params[:device]
    if @device.save
      redirect_to room_device_path(@room, @device), notice: 'Device created'
    else
      render :new
    end
  end


  def update
    @room = Room.find params[:room_id]
    @device = @room.devices.find params[:id]

    if @device.update_attributes params[@device.device_type]
      redirect_to room_device_path(@room, @device), notice: 'Device updated'
    else
      render :edit
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    gon.rooms_index_path = api_rooms_url
    gon.rooms_refresh_delay = 1000
    gon.initial_room_id = Room.first.id
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find params[:id]
    @devices = @room.devices
  end

  def edit
    @room = Room.find params[:id]
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new params[:room]
    if @room.save
      redirect_to room_path(@room), notice: 'Room created'
    else
      render :new
    end
  end


  def update
    @room = Room.find params[:id]
    if @room.update_attributes params[:room]
      redirect_to room_path(@room), notice: 'Room updated'
    else
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devices/_form.html.erb
<%= form_for @device, url: url do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.select :type, DEVICE_TYPES  %>
  </div>


  <%= f.submit class:' btn btn-primary' %>
<% end %>

app/views/devices/edit.html.erb
<%= render 'form', url: room_device_path(@room, @device) %>

app/views/devices/new.html.erb
<%= render 'form', url: room_devices_path(@room) %>

app/views/devices/show.html.erb
<%= link_to "Editar", edit_room_device_path(@room, @device), class: 'btn btn-success pull-right' %>
<h1 class="page-header">Room <%= @device.name %></h1>
<%= @device.description %>

<%= link_to 'Habitacion', room_path(@room) %>

app/views/home/index.html.erb
<h1 class="page-header">Domotic</h1>

<select id="rooms">
</select>


<div id="devices_list">

</div>

<script type="text/html" id="device_lamp">
  <div class="device row" id="device_{{id}}">
    <div class="span4">
      <strong>{{name}}</strong>
    </div>
    <div class="span3">
      {{#status}}
      <span class="label label-success">Encedido</span>
      {{/status}}
      {{^status}}
      <span class="label label-important">Apagado</span>
      {{/status}}

    </div>
    <div class="span2">
      {{#status}}
      <button class="btn btn-danger device_off" data-device_id="{{id}}" data-device_controller="{{device_controller}}">Apagar</button>
      {{/status}}
      {{^status}}
      <button class="btn btn-success device_on" data-device_id="{{id}}" data-device_controller="{{device_controller}}">Encender</button>
      {{/status}}
    </div>
  </div>
</script>



<script type="text/html" id="device_dimmer_lamp">
  <div class="device row" id="device_{{id}}">
    <div class="span4">
      <strong>{{name}}</strong>
    </div>
    <div class="span3">
      <span class="badge">{{status}}</span>
    </div>
    <div class="span2">
      <input class="span1 dimmer_lamp_input" data-device_id="{{id}}" data-device_controller="{{device_controller}}" value="{{status}}">
    </div>
  </div>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservas ADMINISTRACION</title>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= include_gon init: true %>

    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <div class="navbar navbar-fixed-top" >
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Domotic, casa domotica del Gus", root_path, class: 'brand' %>
          <ul id="top_navigation" class="nav secondary-nav pull-right">
            <li><%= link_to "Habitaciones", rooms_path %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div id="log_console">
        <% if alert %>
          <div class="log_error"><%= alert %></div>
				<% elsif notice %>
					<div class="log_notice"><%= notice %></div>
				<% end %>
	    </div>
      <div id="yield">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for @room, url: url do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.submit class:' btn btn-primary' %>
<% end %>

app/views/rooms/edit.html.erb
<%= render 'form', url: room_path(@room) %>

app/views/rooms/index.html.erb
<%= link_to 'Nueva habitacion', new_room_path, class: 'btn btn-success pull-right' %>
<h1 class="page-header">Rooms</h1>
<table class="table table-stripped table-condensed">
  <tr>
     <th>Nombre</th>
     <th>Descripcion</th>
     <th></th>
  </tr>
  <% @rooms.each do |room| %>
    <tr>
      <td><%= link_to room.name, room_path(room) %></td>
      <td><%= room.description %></td>
      <td>
        <%= link_to "Editar", edit_room_path(room) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/rooms/new.html.erb
<%= render 'form', url: rooms_path %>

app/views/rooms/show.html.erb
<%= link_to "Editar", edit_room_path(@room), class: 'btn btn-success pull-right' %>
<h1 class="page-header">Room <%= @room.name %></h1>
<%= @room.description %>


<%= link_to 'Nuevo dispositivo', new_room_device_path(@room), class: 'btn btn-success pull-right' %>
<h1 class="page-header">Dispositivos</h1>
<table class="table table-stripped table-condensed">
  <tr>
     <th>Nombre</th>
     <th>Descripcion</th>
     <th>Tipo</th>
     <th></th>
  </tr>
  <% @devices.each do |device| %>
    <tr>
      <td><%= link_to device.name, room_device_path(@room, device) %></td>
      <td><%= device.description %></td>
      <td><%= device.type %></td>
     <td>
       <%= link_to "Editar", edit_room_device_path(@room, device) %>
      </td>
    </tr>
  <% end %>
</table>